name: Image Builder Template

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean
    secrets:
      GHCR_TOKEN:
        required: false

env:
  # template var
  image: ghcr.io/nel0x/syncthing-lite-builder

jobs:
  build-image:
    name: Build Builder Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v3
        if: ${{ inputs.push }}
        with:
          registry: ghcr.io
          username: nel0x
          password: ${{ secrets.GHCR_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          tags: '${{ env.image }}:latest,${{ env.image }}:${{ github.sha }}'
          push: ${{ inputs.push }}